//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngresosHospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ingresos_HospitalEntities : DbContext
    {
        public Ingresos_HospitalEntities()
            : base("name=Ingresos_HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Ingresos> T_Ingresos { get; set; }
        public virtual DbSet<T_Medico> T_Medico { get; set; }
        public virtual DbSet<T_Paciente> T_Paciente { get; set; }
        public virtual DbSet<Pacientes_Con_Ingresos> Pacientes_Con_Ingresos { get; set; }
        public virtual DbSet<V_Ingresos_Medicos_Pacientes> V_Ingresos_Medicos_Pacientes { get; set; }
    }
}
