//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngresosHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes_Con_Ingresos
    {
        public System.DateTime Fecha { get; set; }
        public Nullable<int> ID { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
    }
}
