//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngresosHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ingresos
    {
        public int ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Habitacion { get; set; }
        public int ID_Paciente { get; set; }
        public int ID_Medico { get; set; }
    
        public virtual T_Medico T_Medico { get; set; }
        public virtual T_Paciente T_Paciente { get; set; }
    }
}
