//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngresosHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Ingresos_Medicos_Pacientes
    {
        public System.DateTime Fecha_de_Ingreso { get; set; }
        public string Nombre_del_Medico { get; set; }
        public string Nombre_del_Paciente { get; set; }
    }
}
